version: '3'
volumes:
  maria-db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/lbonnefo/data/maria-db_data
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/lbonnefo/data/wordpress_data
      o: bind

services:
  maria-db:
    build: requirements/mariadb
    image: maria-db
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - maria-db_data:/var/lib/mysql
    restart: always

  wordpress:
    build: requirements/wordpress
    image: wordpress
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - maria-db
    env_file:
      - .env
    restart: always

  nginx:
    build: requirements/nginx
    image: nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: always

networks:
  inception:
