version: '3'
volumes:
  maria-db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/lbonnefo/data/maria-db_data
      o: bind

services:
  maria-db:
    build: requirements/mariadb
    image: maria-db
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - maria-db_data:/var/lib/mysql
    restart: always

networks:
  inception:
